version: "3.4"

services:
  api:
    # env_file: ./.env
    build: .
    container_name: my_fastapi_api
    environment:
      - MYSQL_DATABASE=fastapi_practice_development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 8000:80
    volumes:
      - .:/app:cached
    depends_on:
      - db

  db:
    image: mysql:8.0.20
    container_name: my_fastapi_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_fastapi_development
    ports:
      - 8306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    cap_add:
      - SYS_NICE
